### ISSUE TITLE
[Question] Best practice Update and Draw

### ISSUE THREAD

**Issue by georg-eckert-zeiss** [Doraku/DefaultEcs#102]
Hi there,

I wonder, is there a best practice in DefaultECS on using Draw and Update methods? Should I use separate systems for that or is it possible to have both methods in Systems. Most game engines separate update and draw logic - like updating everything first and drawing afterwards.

Cheers,
Georg

**Comment by Doraku** [comment]
Hey, there is no forced way to do this in DefaultEcs but usually like you said engine separate the update and draw logic. This is done to more easily use a fixed time update, that way if your game is running late, the engine can run in quick succession multiple times the update logic to catch up to the current time and then call the draw logic only once. Fixed time update is preferred to have a more consistant state update (for example when moving an entity we usually do elaspedTime * acceleration, if the elaspedTime is not constant you may not end up with the same result in your calculation whether you executed it two times with 20ms or once with 40ms because your computer lagged for some reason). Sometimes you want a higher update framerate than the draw one too.
Personally I use Monogame as my engine/framework which include this separation so I use two systems to split my update/draw logic its expected way but you could just as easily put everything in a single sequential system :)
See the sample for a simple examples
https://github.com/Doraku/DefaultEcs/blob/e1936b3b0dfa341fa0bccf8d70098ace4f3e940d/source/Sample/DefaultBoids/DefaultGame.cs#L73

**Comment by georg-eckert-zeiss** [comment]
Alright. Thank you : ) Yeah, I came to that conclusion as well. I am too using MonoGame.
