### ISSUE TITLE
So i've tried to multithread some of my systems...

### ISSUE THREAD

**Issue by nrader95** [Doraku/DefaultEcs#128]
Not using Set, Remove or Dispose restriction on entities is quite straightforward.
But not using other entities is not, so i would like to clarify some things:
1) Is using other entity will lead to problems no matter what i do, or that depends on specific usage?
2) If 1) is not outright forbidden, what are things that is okay to perform? Can i, for example, use other entity, assuming it wont be used by other threads but only current? 

Plus, am i right in assuming that Enable<T>/Disable<T> can be pretty much used as multi-threaded alternative to Set<T>/Remove<T> ?

**Comment by Doraku** [comment]
1. you can use other entities, but the same restriction on the operations apply to them (no Set, Remove, Dispose without using a EntityCommandRecorder)
2. yep, basically read operations are fair game, it's write operations that you need to be careful with (but if you know you are the only one changing the value of a component like so `entity.Get<Component>() = newValue;` for a particular entity it's ok)

I should probably update the documentation about this, it is ALL composition altering operations that shouldn't be done in multithread without using an EntityCommandRecorder, so that's:
- Create an Entity
- Dispose an Entity
- Set/SameAs/SameAsWorld a component on an Entity or a World
- Remove a component on an Entity or a World
- Enable an Entity
- Disable an Entity
- Enable a component on an Entity
- Disable a component on an Entity
- NotifyChanged a component on an Entity

All those operations are not thread safe.

**Comment by nrader95** [comment]
Would be nice to have it all mentioned in docs, especially in XML ones of the corresponding methods.
