### ISSUE TITLE
Changing an entity set breaks systems even in single-threaded applications

### ISSUE THREAD

**Issue by Helco** [Doraku/DefaultEcs#139]
This might very well just be a documentation flaw, but I think it should be mentioned somewhere.
If an application is using `AEntitySetSystem` and during update changes (e.g. removes) an entity from that entity set (e.g. by removing a component or updating such that a predicate is no longer `true`) there are multiple breaking things happen:
  - If the entity was propagated as `in DefaultEcs.Entity` parameter, that reference changes in the middle of an update method
  - The `for` loop advances after the single-entity update practically jumping over one entity.

Workarounds for this issue are:
  - Using EntityCommandRecorder (even though the docs say they are only necessary for multi-threaded applications)
  - Setting the `useBuffer` parameter of `AEntitySetSystem`

**Comment by Helco** [comment]
A minimal reproduction that currently outputs:

```
I was Entity 1:1.0
But now I am Entity 1:2.0
I was Entity 1:2.0
But now I am Entity 1:2.0
```

```csharp
using System;
using DefaultEcs;
using DefaultEcs.System;

class SomeSystem : AEntitySetSystem<float>
{
    public SomeSystem(World world) : base(world.GetEntities()
        .With<bool>()
        .AsSet())
    { }

    protected override void Update(float state, in Entity entity)
    {
        Console.WriteLine($"I was {entity}");
        entity.Remove<bool>();
        Console.WriteLine($"But now I am {entity}");
    }

    public static void Main(string[] args)
    {
        var world = new World();
        var entityA = world.CreateEntity();
        entityA.Set(true);
        var entityB = world.CreateEntity();
        entityB.Set(true);

        var system = new SomeSystem(world);
        system.Update(0f);
    }
}

```

**Comment by Doraku** [comment]
It is "somewhat" mentioned in the xml documentation of [`AEntitySetSystem`](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/AEntitySetSystem_T_.md):

> Represents a base class to process updates on a given EntitySet instance.
> Only Get<T>(), Set<T>(T) and SetSameAs<T>(Entity) operation on already present component type are safe.

but it could help to be a little more documented somewhere in the main readme indeed.

The current implementation aims for as little overhead as possible with no copy so the enumeration occurs on the internal array storing the entities of the set. If you do operations that alter the composition of the entities (and thus this array) you either need to delay those by recording them in an `EntityCommandRecorder` or create the system with `useBuffer` as true so the entities are first copied over to different array internally and this is what is enumerated (it was specifically added for this short coming so it's by design).

**Comment by Helco** [comment]
Just a note: `Set` is also not safe, as this can also cause an entity to be removed when a predicate was set.

**Comment by Doraku** [comment]
ohh that's true! It's not that it is not detailed enough now, it's also wrong :| Thanks for bringing it up.

**Comment by nrader95** [comment]
I think reducing the number of available constructors while making remaining ones want this parameter specified explicitly would be nice addition too. This way people will at least look if they need this parameter set to true instead of wasting time in debugger only to realize they forgot to read some part of docs and did thing wrong.

And same for minEntityCountByRunnerIndex, i think, since sync'ing with runner thread when your number of entities in update barely surpass that of cores can be troublesome as well.

**Comment by Doraku** [comment]
Hum you got a point, I will see to it.
