### ISSUE TITLE
Add entity.Remove(typeof(T))

### ISSUE THREAD

**Issue by darl2ng** [Doraku/DefaultEcs#144]
Me again :-)

It would be nice to have dynamic type support for entity.Remove(type) for certain tasks.

Thanks.

**Comment by Doraku** [comment]
I am not too keen to add reflection code in hot path, if you really need it you can just as easily create an extension method:
```csharp
public static void Remove(this Entity entity, Type type)
{
    typeof(Entity).GetMethod("Remove").MakeGenericMethod(type).Invoke(entity);
}
```
You can remove the reflection overhead and the boxing of the entity by calling `CreateDelegate` instead of `Invoke` and caching the result in a dictionary but I am not convinced by the usefulness of such a method compared to calling directly the `Remove<>` method.

**Comment by darl2ng** [comment]
Agreed, I wanted to open the issue for discussion mostly. 

Given that hot path performance is important, it should be done as extension as you mentioned. However IMO there should be a strategy to centralize caching mechanism, as you did the same thing in your serializers, it would be nice to have some thing for that.

Speaking of serialisers, it also would be nice to expose the component serialiser if possible :-)

**Comment by Doraku** [comment]
Quite late in the reply sorry! Anyway I think providing a caching mechanism like this is completely out of scope of this library and should be done outside of it :) As for the component serialiser the methods are available as static method in case you want to use this serialization for something else than World or Entity. I am using it for my game configuration and my editor data without any problem.
