### ISSUE TITLE
Add SetMaxCapacity overwrite on second call.

### ISSUE THREAD

**Issue by PodeCaradox** [Doraku/DefaultEcs#149]
Hey Doraku,

first thanks again, i love your ECS framework :D
My problem is i call world.SetMaxCapacity<Chunk>(chunks.Length); every time i load a new Map, but dont create a new world. Somehow the other calls after the first SetMaxCapacity are ignored. Is this intended? :)
![grafik](https://user-images.githubusercontent.com/5760157/147693186-0d2e2f85-2a2a-4112-b180-4fbfff1bc816.png)

If you read it in time i wish you a happy new Year :)

**Comment by Doraku** [comment]
This was by design when I added this feature a long time ago, that's why the SetMaxCapacity returns the actual capacity so you would know if the set worked or not. Since then a lot of stuff have changed and I can see this behavior (setting the MaxCapacity only working once for a give component type, and before any component of that type is set) relaxed ;) I will make it so you can change the max capacity if the new value is greater or equals to the current count of components.

> If you read it in time i wish you a happy new Year :)

Thanks a lot I hope you had a great new year eve too ^^
