### ISSUE TITLE
Cannot create EntitySet with both WhenAdded and WhenRemoved

### ISSUE THREAD

**Issue by alexdlm** [Doraku/DefaultEcs#166]
Is there a way to create an `EntitySet` that accumulates entites when a component is **either** added or removed?

ie:
```c#
world.GetEntities()
  .With<Foo>()
  .WhenAdded<int>()
  .WhenRemoved<int>()
```

The above doesn't work currently because `EntityQueryBuilder.WhenAdded<T>` and `.WhenRemoved<T>` call ` .With<T>()` and `.Without<T>()` respectively, the predicate will never match for the removed case.

Ideally there would be a way to build the above query such that the `.With<Foo>` predicate is fulfilled, and subscriptions for the `WhenAdded`/`WhenRemoved `are added without a `When<int>` affecting the predicate.

My current workaround is maintaining two EntitySets, which isn't ideal and I also had to roll my own system to replace `AEntitySetSystem`.

```c#
var addedEntities = world.GetEntities()
  .With<Foo>()
  .WhenAdded<int>();

var removedEntities = world.GetEntities()
  .With<Foo>()
  .WhenRemoved<int>()
```

**Comment by Doraku** [comment]
This is kinda by design ^^" I think it's fair to expect a rule saying "I want entities when a thing is added" to still have this thing when processed and "I want entities when a thing is removed" to not have the thing anymore. Maybe what you need is [SubscribeComponentAdded](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/World.SubscribeComponentAdded_T_(ComponentAddedHandler_T_).md) and [SubscribeComponentRemoved](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/World.SubscribeComponentRemoved_T_(ComponentRemovedHandler_T_).md) so you can store those entities somewhere (as those callback will be synchronous with the actual add/remove operation) and then later on process them?

**Comment by Doraku** [comment]
feel free to reopen this issue if you feel this solution does not satisfy you.
