### ISSUE TITLE
Disposing an entity currently being processed by an AEntitySetSystem

### ISSUE THREAD

**Issue by Cardinal90** [Doraku/DefaultEcs#172]
Here is a minimal Unity test case for what I'm trying to do:

```csharp
using UnityEngine;
using DefaultEcs;
using DefaultEcs.System;

class DisposeSystem : AEntitySetSystem<float>
{
	public DisposeSystem(World world) : base(world) { }

	protected override void Update(float state, in Entity entity)
	{
		Debug.Log($"Removing entity {entity}");
		Debug.Assert(entity.IsAlive);
		entity.Dispose();
	}
}

public class Test : MonoBehaviour
{
	void Awake()
	{
		World world = new World();
		world.CreateEntity();
		world.CreateEntity();

		DisposeSystem system = new DisposeSystem(world);
		system.Update(0f);
	}
}
```

And here is the output:
```
Removing entity Entity 1:1.0
Removing entity Entity 1:2.0
Assertion failed
```

Also an interesting observation: a readonly `EntityId` field changes inside `entity.Dispose()` between the two lines there. Some unsafe shenanigans must be going on :)

After reading #162 I don't think it's a bug, but what is the best solution? You recommend using `EntityCommandRecorder`. There is a problem though. I tried to create a `WorldRecord` in `PreUpdate` and execute it in `PostUpdate`, but I can't save it in a field due to it being a `ref struct`. I haven't encountered many of those. Am I missing something? Or is `useBuffer: true` the only option in my case?

**Comment by Doraku** [comment]
yep as you read it's not "bug", as any operation that changes the entity container during iteration is deemed unsafe. When you need to perform such operations, you can set the flag `useBuffer` to true in the system constructor, that will make entities enumerated copied into an array so even if you make change operation on them (like a dispose), the copies will stay in place. 
The other solution would be to use the `EntityCommandRecorder`. The types produced by the recorder `WorldRecord` and `EntityRecord` are `ref struct` specifically to disallow you to store them anywhere but your current scope, because it would be very dangerous. Internally they point to a specific part of the recorder memory used to register command so it's not something you're supposed to hang to. In your example you would juste do something like `recorder.Record(entity).Dispose();` in the `Update` and call `recorder.Execute();` in the `PostUpdate`.
You could also yourself create a `List<Entity>` in the `PreUpdate`, add your entities to it in the `Update` and then dispose what you have in there in `PostUpdate` but it's basically what the `useBuffer` do for you already.

**Comment by Cardinal90** [comment]
Thank you, it works now!
