### ISSUE TITLE
Improvements to ISystem with Entity Addition/Removal

### ISSUE THREAD

**Issue by captkirk88** [Doraku/DefaultEcs#34]
I don't know this fits in with your design for your ECS.

I propose a addition to ISystem with Added/Removed methods that deal with Entities being added/removed from the world (or activated/deactivated).

This would be useful for dealing with collections that depend on a Entity being active in the world or not and knowing when it is not so that it can be removed from the list/collection.

Even better would be for systems like AEntitySystem to automatically filter Entities based on their relevancy to that system's EntitySet.

Or create a public subscribe event for the end developer to hook into when a entity is added/removed.

If none of those are feasible or in the design strategy, please let me know.  If there is a way to do that in the existing design, I'm all ears.

**Comment by Doraku** [comment]
AEntitySystem already filter entities through their EntitySet (it is their purpose after all) but that only apply on components composition. Do you need the ability to filter on component values? The problem with doing that is you would have to broadcast some sort of ComponentModifiedMessage every time you modify a component (which even if you wanted you can't do since you can change fields of a component without using the Entity.Set<>(component) method). Entity would have to become thread-safe so you could update entities in multi-threading  and that would create huge jumps in the memory every-time you update a component to check interested EntitySet, losing the locality of the cache and jump in predictable way. The performance trade-off would be too much I think.

Now adding events for Entity added/removed is something that was possible in the infancy of this framework (most of [those](https://github.com/Doraku/DefaultEcs/tree/master/source/DefaultEcs/Technical/Message) types were public so you could subscribe on the world to get them. Ultimately I removed them from the public api because it seemed too specific to the internals (and I had no use for it in my game).
I am not against exposing them again (my use-cases is not everyone's and I am all open to new feature suggestions I didn't thought of :]) but could you elaborate on how you need to filter specifically your entities?

**Comment by prime31** [comment]
I think what @captkirk88 is asking for events on an EntitySet like this:

`OnEntityAdded/OnEntityRemoved`

That way a System that is managing a group of Entities knows when it got a new one or lost one so that it can do one-time setup or cleanup.

**Comment by captkirk88** [comment]
Yes that is what I meant.  I was just too tired, at the time, to explain it as well as @prime31 did.

**Comment by Doraku** [comment]
Oh I shouldn't reply as I wake up then I completely misread this.
One problem I have with this is you wouldn't get notified of prior added entities at the EntitySet creation stage, should there be some eligible ones in the world already.
I'm starting to think of some kind of EntityObserver you could pass on an overcharge of EntitySet (and AEntitySystem) constructor with those events preliminary set.
Would something like this be sufficient?

**Comment by captkirk88** [comment]
Yes that would be great.  Thank you.

**Comment by Doraku** [comment]
I think this is what I'll end up adding
```
// presented as an interface, so systems can implement it and pass themselves to their EntitySet
public interface IEntitySetObserver
{
    void OnEntityAdded(Entity entity);
    void OnEntityRemoved(Entity entity);
}

// simple implementation which use event
public class EntitySetObserverEvents : IEntitySetObserver
{
    public event Action<Entity> OnEntityAdded;
    public event Action<Entity> OnEntityRemoved;
}

// overcharge on EntitySetBuilder
EntitySetBuilder.Build(IEntitySetObserver observer)

public interface  IWorldObserver
{
    void OnEntityCreated(Entity entity);
    void OnEntityDisposed(Entity entity);
    void OnEntityEnabled(Entity entity);
    void OnEntityDisabled(Entity entity);
}

public class WorldObserverEvents : IWorldObserver
{
    // you get the idea
}

new constructor World(IWorldObserver observer)

// overcharge on ISerializer
ISerializer.Deserialize(Stream stream, IWorldObserver observer)
```

Did I get everything or is something missing?

**Comment by captkirk88** [comment]
That is everything and more.  Didn't even think about entities being disposed but that will help a lot too with disposing any managed resources attached to them as well.

**Comment by Doraku** [comment]
To manage your resources between entities, may I suggest you have a look [here](https://github.com/Doraku/DefaultEcs#Overview_Resource)? It's still in its infancy but it should already ease the resource management. There is a bug in current version where resources are disposed twice when no longer used though, hopefully your resources won't complain to that ^^".

**Comment by Doraku** [comment]
I added the EntitySet part but I have a second thought on how to handle the World part. I created a new issue for that #36 so I'll close this one in the meantime.
