### ISSUE TITLE
Staging instead of command buffers

### ISSUE THREAD

**Issue by RomanZhu** [Doraku/DefaultEcs#42]
Hi

Have you thought about implementing staging instead of command buffers?
https://github.com/SanderMertens/flecs/blob/master/Manual.md#staging

What do you think about it?

**Comment by Doraku** [comment]
After reading what this is about I have to say I am not convinced (I am no expert though!). I suspect such an implementation would be pretty close or maybe inferior to command buffers performance for benefits I find strange. Modification on an entity in a system should not impact the other entities of this system and if it impacts a different one, it should definitely not run concurrently.
DefaultEcs can be badly misused obviously (say you modify a shared component on multiple entities because of your entity set filter, or Set/Remove a component part of the filter while iterating) which staging would hide from the user, but I would prefer some Roslyn analyzer to warn of bad practices. I should probably open an issue to list what I consider as such for reference actually.

Do you have some examples requiring this approach?

**Comment by RomanZhu** [comment]
Nah, I just wanted to get your opinion :D
