### ISSUE TITLE
How to use DefaultECS to create game loop?

### ISSUE THREAD

**Issue by Morasiu** [Doraku/DefaultEcs#44]
Hi,

First... wow... It's still updated. Good job.

I'm making a terminal game (like in PowerShell or something). I have a problem with creating a game loop. I looked and you used some XNA feature to do it, but that's not gonna work for me. 

Should I make a `SequentialSystem` and update it in some while(true) kind of loop?

**Comment by Doraku** [comment]
Hello, yes calling your aggregation of systems in a while loop is probably the best way (this is basically what is happening in xna/monogame in the game class), you just have to handle correctly your exit condition.
You could also pass a dummy object to the update method if you don't need it, I made it generic so you can chose what you need. In most case it is the elapsed time, but since you are making a terminal game maybe pass an object representing the game state? That way every systems will be able to access and change what they need.

**Comment by Morasiu** [comment]
Ok, Thanks. I'll try to do it and I'll paste the solution here for futiure generations. You are the best!

**Comment by Doraku** [comment]
I added a basic [faq](https://github.com/Doraku/DefaultEcs/blob/master/documentation/FAQ.md#game_loop) where I tried to give a simple enough answer. Feel free to add a more complete one here (or in PR) if you feel like it :)
