### ISSUE TITLE
Do not use LINQ?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#50]
Seems no usage of LINQ loops could make this faster?

https://github.com/Doraku/DefaultEcs/blob/f283587de37ccf6099d0c7f0ceef048959756243/source/DefaultEcs/Technical/EntitySetFilterFactory.cs#L48

**Comment by Doraku** [comment]
This is only the filter creation. While a for "might" be faster (sometimes the jitter just do that on its own anyway, although probably not in this paeticuliar case because of the??) , when not in the hot path I prefer to go for a more readable code style, the factory is cached anyway so if the same filter is needed later it won't even execute this code.

**Comment by dzmitry-lahoda** [comment]
What is the size of loop? If loops does 10K+ times in LINQ than it may be better to replace (to improve game start up time). Other vice close.

**Comment by Doraku** [comment]
Keep in mind this loop is for the either part of the filter construction, one item by group of "or". I would be quite suspicious of an EntitySet requiring 10k different groups of either.
