### ISSUE TITLE
AOT?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#51]
Next seems will not work in AOT.

https://github.com/Doraku/DefaultEcs/blob/f283587de37ccf6099d0c7f0ceef048959756243/source/DefaultEcs/Technical/EntitySetFilterFactory.cs#L57

Any other approaches? May be client site typed builder-combinator? Compile time code gen?

**Comment by dzmitry-lahoda** [comment]
Same for other place of `Compile` usage. 

Consider maxing out using generics and types, like type policy pattern and build stuff from delegates. Or split AOT vs non AOT code. Unity for iOS is no way for now without AOT.

**Comment by Doraku** [comment]
If I am not mistaken, the reason it might have trouble with AoT compilation is because of the code stripping that goes with it. I guess it should be possible to add a config file so AoT compilation will not remove any code from this dll? Looking around quickly I found [this](https://answers.unity.com/questions/1304478/ios-reflection-code-stripping-problem.html]), could this be a solution?

**Comment by dzmitry-lahoda** [comment]
Main reason that secure platforms (like iOS) do not allow JIT. Also they may prevent this because of start up time and batter consumption. So event for Android people do AOT. So call to `Compile` will fail to work as there is no possibility to create new executable code while program is running. I.e. ECS is not usable by most of mobile games.

**Comment by dzmitry-lahoda** [comment]
Solution you have found helps with reflection, but not with compilation.

**Comment by dzmitry-lahoda** [comment]
`Entitas` does work on AOT. 
So I guess some `Compile` can be replaced with generic delegates combination and builder somewhere. Or doing Roslyn codegen.

**Comment by Doraku** [comment]
Hum I see. It should be possible to replace this runtime code generation by static code with some checks but not everywhere. Roslyn codegen might be a good replacement. I will try to look more into that when I am back from my holidays.

**Comment by logixworx** [comment]
So this is a deal-breaker for DefaultECS on mobile?

**Comment by Doraku** [comment]
At least it works on Android as it is my target but I haven't tested it on ios yet (nor windows phone if that's your thing though).

**Comment by dzmitry-lahoda** [comment]
`Compile` compiles code. On iOS as as far as I know you cannot create executable data regions during run time.  

`Compile` can do interpretation, but it is slow and buggy (better write code manually and use cached reflection). Interpretation may require use third party lib either.

On Android Unity IL2CPP `Compile` does not work either even if Android does not preclude run time code gen. IL2CPP(not mono) is for performance. And probably something related to new Google guidelines or new CPU archs.

**Comment by dzmitry-lahoda** [comment]
For code gen, I know these:

1. https://github.com/ltrzesniewski/InlineIL.Fody  https://gist.github.com/dadhi/604d82b884b76b30095d05cce79bf525

2. And https://github.com/dotnet/orleans has nice Roslyn Code Gen

**Comment by Doraku** [comment]
So just some quick stuff:
Currently there is only 2 `Compile` which are important (Serialization can be ignored for now)
https://github.com/Doraku/DefaultEcs/blob/140c6a0533093da1e280d46bfce387a0ddfcd5b4/source/DefaultEcs/Technical/EntitySetFilterFactory.cs#L57
https://github.com/Doraku/DefaultEcs/blob/140c6a0533093da1e280d46bfce387a0ddfcd5b4/source/DefaultEcs/Technical/System/EntitySetBuilderFactory.cs#L57
(side note, quite funny that they are on the same line number :o)

The first one can be easily converted to a lambda for probably the same performance (with some repetition and ugliness to handle the different cases, variables are withoutFilter, withEitherFilter and withoutEitherFilter so 8 possible checks).
Second one can be converted to slow reflection Invoke, or fallback to constructor definition of the Entity instead of using attributes.

I believe I have read somewhere that a property or something was added to know at runtime if code generation was available or not (instead of hopefully calling `Compile` and checking the return/catching an exception) but I can't seem to find it.

Anyway theoretically with those changes and the preservation of code for reflection DefaultEcs should work in AoT/iOS settings. Not sure for IL2CPP as I am not well versed in Unity (is reflection allowed? from a quick search it seems so?) but being compatible with Unity would be a big plus for sure.

**Comment by dzmitry-lahoda** [comment]
>> The first one can be easily converted to a lambda for probably the same performance (with some repetition and ugliness to handle the different cases, variables are withoutFilter, withEitherFilter and withoutEitherFilter so 8 possible checks).

This is the way frameworks are written :) 

>> Second one can be converted to slow reflection Invoke, or fallback to constructor definition of the Entity instead of using attributes.

Can do both? Could create items for Fody or Roslyn generation either.

>> I believe I have read somewhere that a property or something was added to know at runtime if code generation was available or not (instead of hopefully calling Compile and checking the return/catching an exception) but I can't seem to find it.

Have heard same, do not recall name. So you may use exception with TODO to get that handled by others.

>> Anyway theoretically with those changes and the preservation of code for reflection DefaultEcs should work in AoT/iOS settings. Not sure for IL2CPP as I am not well versed in Unity (is reflection allowed? from a quick search it seems so?) but being compatible with Unity would be a big plus for sure.

People will send you example or pull with `link.xml` to prevent AOT code stripping, but that is fine - usual process. Unity is .NET Standard 2.0 and will be 2.1. But no `Compile` or `Emit`. Unity has HUGE game market share. Design of your ECS seems novel(at least for C#) - uses modern C# features. 


>> This would really just be a quick win while waiting for a full code generation at compile time solution using fody/roslyn, and for people who do not want to deal with extra tools in the build chain.

+

**Comment by Doraku** [comment]
So the first has been taken care of, for the same performance (but more code obviously). Hopefully with the new switch syntax and pattern matching it can be ironed out a little.

But I am having conflicting reading on the second one. From what I get reflection to invoke generic methods should work correctly if the code is not trimmed but for IL2CPP I think it's not enough (something about only working for reference generic type parameter for now?)? Then again isn't there some directive for unity to keep the code as c#? After all the is just for the initialisation, not the hot path.

**Comment by shimkovich** [comment]
As was mentioned google already restricts build to necessarily support 64bit archs what forces to use IL2CPP. I can check il2cpp demo build and see if there still any issues.
Defenetely want to give a try to the framework.

**Comment by logixworx** [comment]
I am using it with Unity. Or at least, trying to.  :)

**Comment by arakon5** [comment]
@shimkovich , I was just wondering if you had any results from an il2cpp build?  I'm interested in this framework as well, and would be targeting Unity also.   Thanks

**Comment by shimkovich** [comment]
@arakon5 Sorry, I deffered the project related to the framework, though I still interested in it, maybe @logixworx  tried it out with il2cpp.

**Comment by Doraku** [comment]
I might install Unity to check it since this question has been open for so long haha even if I have no clue how to use it.
From what I gathered
- DefaultEcs.Serialization will not work because of runtime code generation
- DefaultEcs.Command will not work because of reflection to check for unmanged type Set command (I will have to see what can be done here)
- DefaultEcs.System attribute to auto generate the EntitySet in AEntitySystem (WithAttribute, WithoutAttribute, ...) will not work because of reflection use in EntitySetBuilderExtension (but you can force code generation at compile by having EntitySetBuilder.With<> ... explicit call for all the component types you want to use I guess?), building EntitySet yourself should work with the latest preview package since I removed reflection from there
- everything else should work, Unity is supposed to be compatible with c#7.3

**Comment by Doraku** [comment]
Tested on Unity 2020.2.3f1 with version DefaultEcs 0.15.1, Windows platform with IL2CPP runtime.
