### ISSUE TITLE
Instead of null check may be do not allow adding null as system into collection?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#52]
https://github.com/Doraku/DefaultEcs/blob/f283587de37ccf6099d0c7f0ceef048959756243/source/DefaultEcs/System/SequentialSystem.cs#L48

**Comment by Doraku** [comment]
Honestly, I was just lazy with the check :p. This will probably disapear by itself with the final version of C#8.

**Comment by Doraku** [comment]
567382121bf37f1f6ab536a609320755d9641211
Sadly the non nullable reference  feature of c#8 only works for netcore3.0 from what I gathered. Since I want to keep compatibility as low and as wide as possible I don't think relying on it is wise. I might try to activate it on a branch to see how it behaves for older targets but for now I added the checks which should have been there from the start.
