### ISSUE TITLE
Consider some concrete exception

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Doraku/DefaultEcs#56]
https://github.com/Doraku/DefaultEcs/blob/996516e14a40d7bbf956bb74d7319cf871e1dfbf/source/DefaultEcs/Technical/Serialization/BinarySerializer/UnmanagedConverter.cs#L51

And may be ensure that performance is maxed out

https://gitlab.com/dotnet-fun/dotnet-system-except/blob/master/README.md

**Comment by Doraku** [comment]
Yes this exception type is pretty bad. I will see what BinaryFormatter throws  since I like to stick to most of microsoft standard and I dislike creating exception types when a good fit is already there in System.
For your second point, the performance difference should be mainly due to inlining (a method with a throw will not be inlined). In the UnmanagedConverter case, those method are used as delegate so they can't be inlined anyway, using a thrower helper shouldn't make a difference.... For now! I think I have read that there is some sort of static delegate in the work for a futur version of C# which are inlinable and may apply here.

**Comment by Doraku** [comment]
For now I changed those exception to EndOfStreamException, since we are in unsafe territory and do not want to do any check on what is read. The only error we can detect in advance is if the stream ends abruptly to what we expect.
