### ISSUE TITLE
Classes or Structs?

### ISSUE THREAD

**Issue by poettlr** [Doraku/DefaultEcs#58]
Hi, 
I gathered, DefaultEcs can handle both, classes and structs as components; 
Any suggestion on if we should stick to a specific one? 

Currently implementing my components as: 
```
public struct CId : IEquatable<CId> {
        public int value;

        public CId(int id) {
            value = id;
        }
        
        public bool Equals(CId other) {
            return value == other.value;
        }
}
```
or sometimes even 
```
public struct CId : IEquatable<CId> {
        public readonly int value;

        public CId(int id) {
            value = id;
        }
        
        public bool Equals(CId other) {
            return value == other.value;
        }
}
```

Cheers, 
Keep up the good work, and if any assistance can be provided let me know!

**Comment by Doraku** [comment]
Hello, class and struct are a specificity of c# and if you search online for the difference between the two you will find that in some cases it has a huge impact.
To make it short, the ECS pattern try among other things to reduce the number of cache miss when working on a set of data. In memory, a struct is the data itself while for a class it is a reference to a point on the managed memory where the data really is. So when you have an array (what is used to store component in DefaultEcs) of struct, you actually have all your data nicely positioned next to each other so when you enumerate all your entities with a component T, chances are the data for the next entity will already be loaded in the cpu cache, speeding up thing quite a lot (this is also important even if you need to access multiple components for each entity, since the memory will still be accessed in a predictable way).
Now for class, your array only contains addresses to somewhere in the memory, which you have absolutely no guarantee will be next to each other, and even if they were the GC could move things around to compact the managed memory.
An other important thing in a managed language like c# is that you want to minimize the stress on the GC so it doesn't start a collect while you are in your gameplay loop. Every new class object you make add a little stress while struct don't (actually they do because DefaultEcs reallocate a new array if needed but you probably get it, once you have initialized your scene and your entities, no more allocation should occur).

So I would advise to stick to struct for component as much as possible but that doesn't mean you can't use class (or interface even!) if it makes sense. For example I have a IInputController interface set on my player entity, that way I can set different controller implementation (keyboard, mouse, touchscreen, joystick, ...) without changing my update logic. There is not a lot of players (just one for now actually :p) so the loss is minimal.

**Comment by poettlr** [comment]
Sure, I know about all that :D (but thanks for reminding me)

I just know from different ECS systems that some handle a specific type of component (say classes) better. It's more a question for any specific under the hood but since you rely heavily on span and the likes I guess I could have just not asked at all and look at the code before that x)

**Comment by Doraku** [comment]
Sorry I hope it didn't read too patronizing ^^"

If you took a look at the code you might have seen that components are accessed by an indirection, the id of the entity giving the index of the component to finally get the component. I could have just put a single array and used the id of the entity as index directly but despite the overhead there is 3 advantages:
- you can have the component tightly packed and give access to the components without the entities (`world.GetAllComponents<>()`)
- less wasted space because not all entities are going to have every component types
- it is possible to share components between entities (`entity.SetSameAs<>()`)

For class component, the first two are kinda irrelevant (an array of index and an array of reference is the same size in 32bits, a factor 2 in 64bits, and you are going to jump in memory to get to the class data anyway) so that indirection is kinda useless. The third point is more or less achievable (you can set the same class instance on multiple entities to share it, though you wouldn't be able to override the instance with a new one for all entities) so there is that. Maybe it is possible to use different ComponentPool implementation depending of what you want to sacrifice, but for now I think it works well enough in most cases :)

**Comment by poettlr** [comment]
Perfect thanks for the info!
