### ISSUE TITLE
High amounts of components seem to have an overhead on systems

### ISSUE THREAD

**Issue by poettlr** [Doraku/DefaultEcs#59]
Hi, 
I created a very simple test case: 

Consider the following simple system: 
```
public sealed class UpdateSystem : AEntitySystem<float> {
        public UpdateSystem(World world, SystemRunner<float> runner, EntitySet set)
            : base(set, runner) {
        }

        protected override void Update(float state, ReadOnlySpan<Entity> entities) {
            for (int i = 0; i < entities.Length; i++) {
                Console.WriteLine("Iteration");
            }
        }

        protected override void Update(float elaspedTime, in Entity entity) {
        }
}
```

And the following Unit Test: 
```
[Test]
public void MultipleComponents() {
            var world = new World(1024);
            var entity = world.CreateEntity();

            entity.Set(new GenericComponentA {value = 10});
            entity.Set(new GenericComponentB {value = 10});
            entity.Set(new GenericComponentC {value = 10});
            entity.Set(new GenericComponentD {value = 10});
            entity.Set(new GenericComponentE {value = 10});
            entity.Set(new GenericComponentF {value = 10});
            entity.Set(new GenericComponentG {value = 10});
            entity.Set(new GenericComponentH {value = 10});
            entity.Set(new GenericComponentI {value = 10});
            entity.Set(new GenericComponentJ {value = 10});
            entity.Set(new GenericComponentK {value = 10});
            entity.Set(new GenericComponentL {value = 10});
            entity.Set(new GenericComponentM {value = 10});
            entity.Set(new GenericComponentN {value = 10});
            entity.Set(new GenericComponentO {value = 10});
            entity.Set(new GenericComponentP {value = 10});
            entity.Set(new GenericComponentQ {value = 10});
            entity.Set(new GenericComponentR {value = 10});
            entity.Set(new GenericComponentS {value = 10});
            entity.Set(new GenericComponentT {value = 10});
            entity.Set(new GenericComponentU {value = 10});
            entity.Set(new GenericComponentV {value = 10});
            entity.Set(new GenericComponentW {value = 10});
            entity.Set(new GenericComponentX {value = 10});
            entity.Set(new GenericComponentY {value = 10});
            entity.Set(new GenericComponentZ {value = 10});

            Stopwatch sw = Stopwatch.StartNew();
            var set = world.GetEntities()
                .With<GenericComponentA>()
                .With<GenericComponentB>()
                .With<GenericComponentC>()
                .With<GenericComponentD>()
                .With<GenericComponentE>()
                .With<GenericComponentF>()
                .With<GenericComponentG>()
                .With<GenericComponentH>()
                .With<GenericComponentI>()
                .With<GenericComponentJ>()
                .With<GenericComponentK>()
                .With<GenericComponentL>()
                .With<GenericComponentM>()
                .With<GenericComponentN>()
                .With<GenericComponentO>()
                .With<GenericComponentP>()
                .With<GenericComponentQ>()
                .With<GenericComponentR>()
                .With<GenericComponentS>()
                .With<GenericComponentT>()
                .With<GenericComponentU>()
                .With<GenericComponentV>()
                .With<GenericComponentW>()
                .With<GenericComponentX>()
                .With<GenericComponentY>()
                .With<GenericComponentZ>().Build();
            Console.WriteLine("Create 26 Component Set: " + sw.Elapsed.TotalMilliseconds);

            sw = Stopwatch.StartNew();
            var set1 = world.GetEntities()
                .With<GenericComponentA>().Build();

            Console.WriteLine("Create 1 Component Set: " + sw.Elapsed.TotalMilliseconds);
            
            sw = Stopwatch.StartNew();
            var system = new UpdateSystem(world, new SystemRunner<float>(1), set);
            Console.WriteLine("System Creation 26 Component Set: " + sw.Elapsed.TotalMilliseconds);
            sw = Stopwatch.StartNew();
            system.Update(1f);
            system.Update(1f);
            system.Update(1f);
            Console.WriteLine("System Execution 26 Component Set: " + sw.Elapsed.TotalMilliseconds);
            
            sw = Stopwatch.StartNew();
            var system1 = new UpdateSystem(world, new SystemRunner<float>(1), set1);
            Console.WriteLine("System Creation 1 Component Set: " + sw.Elapsed.TotalMilliseconds);
            sw = Stopwatch.StartNew();
            system1.Update(1f);
            system1.Update(1f);
            system1.Update(1f);
            Console.WriteLine("System Execution 1 Component Set: " + sw.Elapsed.TotalMilliseconds);
        }
}
```

All generic Components are simple structs: 
```
public struct GenericComponentA {
        public int value;
}
```

The output of the "test" is: 
Create 26 Component Set: 54.3276
Create 1 Component Set: 0.0233
System Creation 26 Component Set: 2.1566
Iteration
Iteration
Iteration
System Execution 26 Component Set: 4.0623
System Creation 1 Component Set: 0.002
Iteration
Iteration
Iteration
System Execution 1 Component Set: 0.0006

So my assumption is that each added component creates an overhead? I then switched out the struct components for classes which reduced the time taken to create the 26 Component EntitySet from 54ms to 2ms. But the iterations time is still the same. 

I know its not a very good test case, but that seems to be a crucial issue, any idea if it is just a usage error or something in the library itself? I'd expect it should take roughly the same amount of time since its the same entity we are touching? 

Cheers, thanks!

**Comment by Doraku** [comment]
Hum, it is possible to do performance unit test but it is usually quite difficult to do right.
Normally you shouldn't have any difference when enumerating a set, should it has been created with 1 component or 42 so what you are experiencing makes me think this is just the jitter working its magic on the first execution (the 26 component set), which doesn't happen for the second execution. To check that easily, you should inverse both set and see if you have the same result but keep in mind that a single execution is quite poor to benchmark performance. I'll add some test on the benchmark project just to be sure there is not something I missed.

**Comment by Doraku** [comment]
https://github.com/Doraku/DefaultEcs/blob/master/source/DefaultEcs.Benchmark/DefaultEcs/MultipleFilterImpact.cs

|     Method | EntityCount |     Mean |    Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|----------- |------------ |---------:|---------:|---------:|------:|------:|------:|----------:|
|        Set |      100000 | 291.5 us | 5.592 us | 3.699 us |     - |     - |     - |         - |
|       Set2 |      100000 | 290.6 us | 5.645 us | 3.734 us |     - |     - |     - |         - |
|  SystemSet |      100000 | 291.8 us | 5.774 us | 3.819 us |     - |     - |     - |         - |
| SystemSet2 |      100000 | 293.0 us | 4.518 us | 2.988 us |     - |     - |     - |         - |

As for the creation time, generic in c# is basically the jitter producing runtime code as needed. In the case of the 26 component set, that means 26 new method will have to be processed at runtime to be called the first time. Add to that for each component you add to the filter, we will have 2 subscriptions to do behind the scene so the EntitySet can receive notification of potential entity. Add all of that and you end up with this big first cost. The generic time is only paid the first time but the subscription we can't do without. Still I think it is better to have a fast execution path and a slower initialization.
Now I believe the improvement in the creation you see when changing for class is because the jitter actually do not have to create multiple runtime code for the different component in this case. All class can share the same code (they are the same size, the size of a reference) so you only really pay the subscription cost. If you create the big system with struct twice and only measure the second creation, you should see more or less the same time since you wouldn't have to pay the generic cost anymore.

**Comment by poettlr** [comment]
Thanks for the clarification!
