### ISSUE TITLE
Tag system

### ISSUE THREAD

**Issue by MarkWilds** [Doraku/DefaultEcs#67]
Currently the common pattern to get specific entities is by **tagging** them with erroneous/empty components.

To me this feels a bit weird but could understand if this is done because of an already established and working component filter system.

My idea is to add string tags and use for example a [WithTag(“player”)] attribute to also filter with tags.

**Comment by Doraku** [comment]
Indeed, internally component types are assigned a bitmask value so EntitySet can quickly check entities composition without the need to access the componennt values.
Knowing that, I guess nothing stop me to assign bitmask to a special tag value hum...
Note that this should be slower than using empty types as Tag because it would have to look into a dictionary for the tag bitmask, while type tag use a generic shortcut to get it directly.

As I think on this, the curent type tag system seems more powerful to me (there is already some optimisation to reduce the memory needed for them, and I think I can reduce it even more now that I looked at it again). Appart from the oddness of empty struct, is there something you can't express with current api?

**Comment by MarkWilds** [comment]
I can express everything with the current "tag" API.
I guess I can categorize "tag" components in their own folder postfix them tag ;)

**Comment by Doraku** [comment]
Just putting it here because the idea of custom tag has grown on me but I can't really find a real use case, and there is a lot of problem to consider!
```
//new type holding the bitmask internally
public struct Tag
{
    // just for cosmetic, not actually used
    public readonly string Name;
    public readonly string Description;
}

// new World type methods
public static Tag CreateTag(string name, string description);

// new Entity type methods
public void SetTag(Tag tag);
public void RemovedTag(Tag tag);
public bool HasTag(Tag tag);

// new EntitySetBuilder methods
With(Tag tag) Without, WhenAdded, WhenRemoved ...
```
so with all that we could dynamically create tags without the need of new types, with the same performance of the existing system. The user just handle his custom tags happily, even re purposing them across different World instances if he wants but there is a couple of problem:
- Tag are created statically and exist for all World (currently this is done for component type so the filters are shared across all instances, to speed up the start up and execution)
- WithEither mixing type and tag will be a big mess!
- You can't use the Attribute declaration for them on AEntitySystem (only const value can be used to init attribute value)
- Serialization would be a horrible to handle! (or make the name act as a key, but still horrible)
