### ISSUE TITLE
GetChildren().With<Component>() ?

### ISSUE THREAD

**Issue by Ashe** [Doraku/DefaultEcs#71]
Hey there. So I'm trying to compose a scene and I have a component named `Map`. I have a system that iterates through every entity with the `Map` component. My plan was to use `GetChildren()` to get the entities, and then only use the ones that have certain components.

Retrieving all the children is probably inefficient in comparison to the `EntitySet` functionality you have, the reason I can't really use that is I have data in the `Map` component I want to use while processing the children; retrieving that data while processing the child is also problematic due to being able to have multiple parents / not being the main focus of parenting as discussed in this issue: https://github.com/Doraku/DefaultEcs/issues/33

Just throwing out a question as to whether this functionality would be good or whether there's a reason that it's not possible to do `With<Component>()` after getting children. Thanks!

**Comment by Doraku** [comment]
Every time I see GetChildren I wonder what got into me to put this feature in this state x)

EntitySet are only interested on component composition by design, as component types are assigned a bitmask as they are used, making the check of inclusion of an entity to a set efficient.
To handle this I can think of some possibilities

The ugly: you can filter child entities by using IsEnabled<T> or Has<T> (weither you care only for existence or if the component is active) to check the child composition and do you thing. This rely on GetChildren (uhhhhhhg) and a slow check.

The bad: I could add a Contains method on EntitySet (actually I will do that, it should have been there from the start) so you can filter faster the child entities with their composition, but you still need to use GetChildren (grrr).

The TBD: as you cite issue #33, do your use case actually need multiple parent? As in different parents for the same impacting system? If this is not the case (ex: one parent for render to have a relatif position, one parent for some other unrelated system,... ) you could set up a generic parent component so you can filter on a specific type, so the children could retrieve what they need as they are processed (if you only have a max depth of one...). A mechanism like this has been on my todo for a while but I haven't found a good fit yet to handle any depth.

If you need multiple parents for the same processing, I will have think a little more to come up with something  better than GetChildren!

**Comment by Ashe** [comment]
I don't need multiple parents and I don't think that's a very good idea at all to be honest. I can't see what multiple parents could achieve that simple changes to your component setup couldn't - however the ability to have a single parent and operate on that relationship could be very powerful for people who need it.

My use case, while inefficient, is okay. The children will only have one parent, but there may be multiple entities designated as `Map`s being rendered on screen at once, for instance.

Just for your information I'll show you what I'm doing:

```cs
        // Draw all entities with axial coordinates
        public void Update(SpriteBatch spriteBatch) {

            // Don't do anything if disabled
            if (!IsEnabled) { return; }

            // For each map
            EntitySet maps = _world.GetEntities().With<Map>().Build();
            foreach (Entity mapEntity in maps.GetEntities()) {

                // Retrieve the current map that's being rendered
                var map = mapEntity.Get<Map>();

                // Iterate through entities on the map
                foreach (Entity e in mapEntity.GetChildren()) {

                    // Only operate on children with PixelCoords and AxialCoords
                    if (e.Has<AxialCoord>() && e.Has<PixelCoord>()) {
....
```
Basically, the map will contain data such as how the map should be rendered (spritesheet, shaders or whatever) as well as sizes of the tiles. This system will then render the game using that data. There's no use storing this information in all the components as they don't care as long as they all have the same, so grouping them all as children of this `Entity` containing `Map` is what I'm doing.

I know there's a system that iterates through `Entity`s with specific component setups using `EntitySet`, but its important that I have the data for `map` on hand that every `Entity` will need each frame. I imagine `Get<Map>()` for each child would be more efficient than what I'm doing, but I'm not planning for `Map` to have children that aren't targeted by this `System` (as the more children the `Entity` has the slower this will become as we know). 

I'm building my game around this design, I just wanted to ask the question for the future as it would certainly make things quite convenient. 

I imagine this would be easier to implement if you decided for the single-parent approach, as `EntitySet` might be a lot easier to rework when you just need to do an equality check on the given `Entity` and the parent of the `Entity` being checked while using `EntitySet`. 

Loving the ECS! This is my only complaint and I think its a pretty small one :) I just can't really use your nicely pre-defined `System` classes as I'd want to do things before and possibly after the iteration of `Entity`s, as I do in the snippet above.

**Comment by Doraku** [comment]
>I don't need multiple parents and I don't think that's a very good idea at all to be honest.

Definitely, the SetAsParentOf/SetAsChildOf was not designed for this but I get why people would use it this way.
>however the ability to have a single parent and operate on that relationship could be very powerful for people who need it.

This is one of the big missing piece I really hope to fill soon, but I keep working on other stuff :(

So basically you want to render multiple scenes on different part of the screen? First off, I hope you dispose of `maps` at the end of the update or you would have best case a lot of garbage on the gc, worst case memory growing ^^". You should create this EntitySet in the constructor of your class.
If your entities can only have one parent, you could set the Map component as shared between all the child (`child.SetSameAs<Map>(parent)` if it is a struct, if it is a class you can even use the regular Set to set the same Map instance) so you can use the usual filter construction (`With<Map>().With<AxialCoord>().With<PixelCoord>()`).
If you want to keep the component on the parent only, you could set the parent as a component of the child instead ^^" (`child.Set<Entity>(parent)`, an ugly hack but hey!).

> Loving the ECS! This is my only complaint and I think its a pretty small one :) I just can't really use your nicely pre-defined `System` classes as I'd want to do things before and possibly after the iteration of `Entity`s, as I do in the snippet above.

Thanks :) but I think it is a pretty big one! I should really focus on this. You have a PreUpdate and PostUpdate methods you can override to things around the iteration of entities btw in the base AEntitySystem.

**Comment by Ashe** [comment]
> If you want to keep the component on the parent only, you could set the parent as a component of the child instead ^^" (`child.Set<Entity>(parent)`, an ugly hack but hey!).

The `Set<Entity>` option could work pretty well actually, didn't think of that! 

> `SetSameAs<Map>(parent)`

Wait, I always thought this just duplicated a component. Does this literally create a component that is shared between `Entity`s? If the original is edited, the entities all update okay? Should make a note of that. I could go down that route, but it'd then be hard to differenciate the different maps from each other.

> I hope you dispose of maps at the end of the update or you would have best case a lot of garbage on the gc

Thanks for the warning. I'm used to C++ and I have only just started learning C#. I am struggling a bit with memory, knowing whether something is a reference or not. I just assumed that the maps I made went out of scope at the `}` and got cleaned up but obviously my understanding is very imature.

There is another small idea I had - I have a `global` entity where the idea is that I have some `Component`s with a maximum count of 1 that all get added to it. It means I can just use the ECS as easy storage of any class I want that know of the `World`. I got the idea from an ECS I used with `Haskell` called [Apecs](https://github.com/jonascarpay/apecs) and I haven't really seen it in the ECSs I've used in C++. This is the first C# ECS I've used so just throwing it out there - you basically store the entity with the index of 0 or -1 or someting as the 'global' entity and can essentially 'give' it to the world in the same way that you set the `maximumCount`. 

While this doesn't apply to my use case as I'm trying to keep all paths open (I don't know if I want to render multiple maps but I don't want to lock myself out of it), someone else may have a similar idea and make this `Map` component global instead of on an entity like I have. With my current setup I just need to save a reference to my global entity which isn't that clean but its good enough - but yeah that's another thing you could consider :)

**Comment by Doraku** [comment]
> Wait, I always thought this just duplicated a component. Does this literally create a component that is shared between `Entity`s? If the original is edited, the entities all update okay? Should make a note of that. I could go down that route, but it'd then be hard to differenciate the different maps from each other.

Yes it was specifically done for that, even if your component is a struct (if you are starting c#, you should look into class and struct differences as it is really important for the memory, especially to limit the memory pressure on the garbage collector, so your game doesn't freeze because of GC.Collect). As you said it is easy to lose sight of what is shared or not so use it with caution. I try to make my compositions so that only the "owner" of the component will update its value and the other entities are updated in a different system where they will only read the value.

> I just assumed that the maps I made went out of scope at the `}` and got cleaned up but obviously my understanding is very imature.

Even if it does go out of scope, you never now when the gc will actually cleanup this memory, it might happen at the worst time when you don't want to lose time for a frame. In this case, I think it can't even reclaim the memory of the EntitySet because you didn't dispose it (there is some delegate subscriptions done behind the scene so the EntitySet can be updated as you add/remove component on your entities, keeping it alive and ineligible for collection). As a rule of thumb, if something is IDisposable, call Dispose on it when you are done with it, or use the `using` construct.

As for global static, while this is something easily achievable, I think it is better to leave it to the users, kinda overkill to use a World and Entity to share object across your program when you can declare static fields/properties to be accessible everywhere anyway :). Personally I try to stay clear of singleton but that's just my style.

**Comment by Ashe** [comment]
Thanks for the lessons! I guess I'll close the issue as there isn't really anything to discuss anymore :)
