### ISSUE TITLE
How to wire unity's view and entity

### ISSUE THREAD

**Issue by neronmoon** [Doraku/DefaultEcs#78]
Hey! First of all, big thanks for great product! 👍 👍 👍 

I've started using it, but stuck at point of wiring Unity's GameObject with entities.
In Entitas i have full access to entity events like ComponentAdded/ComponentReplaced/ComponentRemoved, 
but i didn't find elegant solution for this thing in DefaultlEcs.

I've found, that ComponentAddedMessage marked as internal. Is there any serious reason for that?

**Comment by Doraku** [comment]
Hello :)
My reasoning for making all those stuff internal was to expose an API as simple as possible with little risk for users to do stuff they are not supposed to do. For example in the ComponentAdded/Changed/... Message only the entity id is passed instead of the full Entity item to minimize copy, and the ComponentEnum is not immutable, again to minimize copy, so keeping all that internal allow me to assume that the state will not get corrupted and keep the best performance.  Hopefully I have not been over conservative in my approach ^^"
I have not a lot of knowledge of unity sadly (some people asked about compatibility of this library #51, maybe you could confirm if it is actually compatible?), by wiring I suppose you mean with the GUI? Since this is design time maybe you could use a similar approach to the [DebugComponentReader](https://github.com/Doraku/DefaultEcs/blob/4f2410850432eb0e98ced4ec8a9892390231c8d7/source/DefaultEcs/Technical/Debug/EntityDebugView.cs#L26) I am using to enhance the debugging experience? What is actually needed for Unity's view if I may ask?

**Comment by neronmoon** [comment]
Yeah, DeafaultECS is compatible with Unity, but i've just started using it, so i may be wrong :)

By wiring i mean following:

I like to use ecs stuff fully separate from render layer (which is Unity). So for example, i've created entity Player which should be rendered as some sprite and other component by Unity. Player has components: position, health etc. Theese components should be mirrored to some UI in Unity. To do so, i've wrote InstantiateViewSystem:
```csharp
ResourceComponent resource = entity.Get<ResourceComponent>(); // This component holding link to prefab

GameObject go = GameObject.Instantiate(resource.Value); // creating Unity's GameObject
EntityLink link = go.AddComponent<EntityLink>(); // Adding component to game object that have link to DefaultECS entity
link.Link(_world, entity); 
entity.Set(new ViewComponent {Value = go}); // Link entity to game object
entity.Remove<ResourceComponent>(); // Remove Resource component after linking
```
What i want is to trigger some GameObject's components functions when any component on linked entity is added, updated or removed. Theese functions will show animations, change sprites etc.

I'll try to do it with your reader approach, but i think some entity events still should be exposed

**Comment by Doraku** [comment]
hum, even if I were to make those event public you would have trouble to subscribe to all of them as they are generic to component type. A simpler approach would probably for you to wrap the Entity.Set method (maybe make an extension) so you can fire your general event to make unity ui react to it:
```
public static event Action<Entity, Type> ComponentSetted;
public static event Action<Entity, Type> ComponentRemoved;

public static void UnitySet<T>(this Entity entity, in T value = default)
{
    entity.Set(value);

    // probably some check to only fire that event in design time to not slowdown in release mode
    if (designTime)
    {
        ComponentAdded?.Invoke(entity, typeof(T));
    }
}

public static void UnitySetSameAs<T>(this Entity entity, in Entity reference) ...

public static void UnityRemove<T>(this Entity entity) ...
```

That do mean you would have to wrap all those calls to get the events sadly, and you would need to handle if the Set/Remove actually added/removed the component, I should probably change them to return a bool actually >_>

**Comment by neronmoon** [comment]
So i've ended up with simplies solution -- creating `EntityMutator` class, that triggers `Set<>` and `Remove<>` on entity and does some events triggering on linked view object.

That EntityMutator can be easily accessed with `Mutate()` extension method on Entity.
```csharp
public static EntityMutator Mutate(this Entity entity) {
    return new EntityMutator(entity);
}
```
I think this is kinda sorta fine solution, except i should always remember to mutate entities ONLY via mutator.

Hope, that will help some folks that will use that ecs implementation.

**Comment by neronmoon** [comment]
I've implemented my approach in #83 Lets discuss it!

**Comment by Doraku** [comment]
Sorry for the late response but between Christmas and new year eve it's hard to find time!

While I get the motivation behind such changes I am not convinced by the trade-off. Making all those calls virtual would lose the benefit of inlining and add extra indirections with the access of the World property (I expect some loss in the benchmarks because of this), and letting users override the EntityAccessor/Mutator with no guaranty that the provided instance will do what needs to be done seems dangerous to me.
As you have done before, creating your own wrapper for entity/world is simple enough ([and you are not the first doing so](https://github.com/Doraku/DefaultEcs/issues/36#issuecomment-481933369)) with no added complexity to DefaultEcs. There is still the question of exposing more events so you can add your custom logic to inner world events, making it easier and less error prone to forget to use your wrapper but I have yet to find a satisfying solution (yeah I am really picky sorry for that ^^")

**Comment by neronmoon** [comment]
That's ok! Thank you for reply. 
In my programming experience it nearly impossible to give an ability to extend the framework and make it 100% error-proof. Also, we are all programmers here so i think if danger places are nicely covered in docs it wouldn't become a problem :)

**Comment by Doraku** [comment]
I thought the first ones to not read the documentation were programmers :p

Just ran the benchmark for system update, I will let it speaks for itself ^^"
Your branch:
```
|                   Method | EntityCount |       Mean |    Error |   StdDev |     Median | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------- |------------ |-----------:|---------:|---------:|-----------:|------:|------:|------:|----------:|
|  DefaultEcs_UpdateSingle |      100000 | 3,409.8 us |  7.05 us |  6.25 us | 3,410.0 us |     - |     - |     - |         - |
|   DefaultEcs_UpdateMulti |      100000 |   912.1 us | 18.13 us | 28.22 us |   902.7 us |     - |     - |     - |         - |
| DefaultEcs_Update2Single |      100000 | 3,233.8 us |  5.74 us |  5.37 us | 3,234.9 us |     - |     - |     - |         - |
|  DefaultEcs_Update2Multi |      100000 |   844.4 us | 12.71 us | 11.26 us |   842.2 us |     - |     - |     - |         - |
|     DefaultEcs_UpdateTPL |      100000 |   942.4 us | 18.61 us | 37.60 us |   914.4 us |     - |     - |     - |   32768 B |
```
Master:
```
|                   Method | EntityCount |     Mean |   Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------------- |------------ |---------:|--------:|---------:|------:|------:|------:|----------:|
|  DefaultEcs_UpdateSingle |      100000 | 675.0 us | 2.05 us |  1.92 us |     - |     - |     - |         - |
|   DefaultEcs_UpdateMulti |      100000 | 245.2 us | 4.85 us | 10.01 us |     - |     - |     - |         - |
| DefaultEcs_Update2Single |      100000 | 601.5 us | 1.46 us |  1.29 us |     - |     - |     - |         - |
|  DefaultEcs_Update2Multi |      100000 | 245.4 us | 4.87 us |  9.02 us |     - |     - |     - |         - |
|     DefaultEcs_UpdateTPL |      100000 | 289.4 us | 5.79 us |  7.32 us |     - |     - |     - |   32768 B |
```

I expected a slowdown but a 4-5 factor is really huge, definitely need a different approach.

**Comment by Doraku** [comment]
This problem has been haunting me for a while but I may have come up with a satisfying way to help you get component events:
```
    public interface IComponentObserver<T>
    {
        void OnAdded(in Entity entity);
        void OnChanged(in Entity entity);
        void OnRemoved(in Entity entity);
        void OnEnabled(in Entity entity);
        void OnDisabled(in Entity entity);
    }

    // new api on World type
    public IDisposable SubscribeComponentObserver<T>(IComponentObserver<T> observer);
```
I am closing on making everything works as expected. Only throw back would be that you have to manually subscribe for every component types in use, so I may introduce a non generic IComponentObserver with generics methods to remedy this.

**Comment by Doraku** [comment]
You should have everything you need now to hook up on component events now. You should not do performance sensitive action using this but to synchronize DefaultEcs with Unity ui as design time it should do the job.
