### ISSUE TITLE
Feature request: Unique (singleton) components

### ISSUE THREAD

**Issue by neronmoon** [Doraku/DefaultEcs#85]
I've been watching very cool GDC talk about implementing ECS in Overwatch (https://youtu.be/W3aieHjyNvw?t=716) and realized, that this Unique components are pretty common in game development. For example you can only have one InputComponent, TimeComponent etc.
I think it's a good thing to implement in DefaultECS! :)

**Comment by Doraku** [comment]
Thanks for the great talk, really amazing stuff in the netcode part.

Currently singleton component are already more or less supported (can be enforced at runtime but not really at build time).
Already handled singleton component types are the flag ones, struct with no members. But those are boring stateless component, handy to tag entities as you need, not so much to share states between multiple entities. Although you could use a tag to state that your entity is allowed to access your singleton stored somewhere else.
You could enforce a singleton component by [setting the maximum number of a given component type](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-World-SetMaximumComponentCount-T-(int).md) to 1, thus forcing you to use [Entity.SetSameAs](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-Entity-SetSameAs-T-(DefaultEcs-Entity).md) to share the single allowed component instance between all your entities (use a "master" entity to set the component once or something like that).

Could this be improved? I could add an Attribute to decorate your component type you would want to use as singleton (automatically doing the SetMaximumComponentCount for your behind the scene) but I feel it would be too limiting. The main problem you see in singleton pattern discussion (apart from the fact that it is not a pattern) is that the type itself should not hold restriction on its lifetime management (the container of your singleton instance can't be the type itself, for separation of concern and testability). Making a singleton declaration by attribute would mean you could not declare as singleton a type not part of your code base (usually frequent when you use a graphic library), nor use it as a singleton or not depending of your use-case. And you would trade one line (`SetMaximumComponentCount`) for an other (`[Singleton]`), not an interesting trade-off.

If you have a better alternative don't hesitate to share it :)

**Comment by jnoyola** [comment]
If I understand correctly, your `ComponentPool<T>` is typed for a specific component type, and pools for different component types can each have their own capacity. So having a component where you set the maximum capacity to 1 should be a perfect (although, as you say, not quite automatic) solution, because you're not wasting time or space with multiple of these components.

This is in contrast to a hypothetical implementation that stores a buffer for each component type, each with the same length as the number of entities. In that case, if you had 1000 entities with a `PositionComponent`, you would also have room for 1000 `InputComponent`, which you don't want.

And I agree you'd want the container to control the lifetime, so I think your solution is perfect.

**Comment by Doraku** [comment]
Yes, since memory space is usually a big limitation of video game I wanted to give the tools to limit the component spaces if you know your usage. In its first versions DefaultEcs was actually closer to your hypothetical implementation haha now it grows internal arrays as needed with a max capacity you can set. It might generate some garbage as you setup your entities but it is not greedy on the memory anymore and once your World has stabilized those size shouldn't change a lot.

Looking back at this issue I think their is a way to have a more straightforward singleton but what would happen here:
```
// hypothetical api
world.SetSingleton<SingletonType>();

entity.Set(singletonInstance);

// should this set singletonInstance as the value for entity2 or change the shared value to newSingletonInstance for entity and entity2?
entity2.Set(newSingletonInstance);
```
Maybe it is better to keep current usage which force you to use SetSameAs hum...

**Comment by jnoyola** [comment]
Maybe singletons you could just get and set on the `world`, or maybe there's some `world.SingletonEntity` that has all the singleton components.

**Comment by Doraku** [comment]
Setting the component directly on the World wouldn't give any benefit, you could just store the singleton instance on the side yourself, the problem is making it part of an entity composition. I am not too keen on adding a new api on the Entity class just for singleton and I can't come up with a way to make it works with the existing methods in a way that makes sense :/

**Comment by jnoyola** [comment]
What do you think about storing these on the state, in addition to elapsed time? Render settings, maybe user inputs, anything that needs to be passed between systems or stored for longer than one frame that only has a single copy and isn't tied to an entity. Is there any reason the state needs to be immutable, serializable, or have a well-defined `Equals` override?

**Comment by Doraku** [comment]
Oh yeah definitely you can do whatever you want with the state passed in systems! I let it generic specifically for this reason :) there is actually no constrains on it too, the sky is the limit!

**Comment by Doraku** [comment]
Just closing this old issue, to recap you can already enforce single instance component for a given type, or you can just store your singleton in the state you will pass to your systems for the update (and maybe use a tag component to easily check which entity should actually access this singleton).
