### ISSUE TITLE
Enitity structure

### ISSUE THREAD

**Issue by RomanZhu** [Doraku/DefaultEcs#90]
I have 2 questions about Entity struct
1) https://github.com/Doraku/DefaultEcs/blob/566186706360454e483137b9aaea3a7682da533b/source/DefaultEcs/Entity.cs#L26 
Why version is just short? Not even `ushort`
In unity they use 32bit field for that. So wrap-around won't happen so frequent (which can be a problem in a long-running game)
2)
https://github.com/Doraku/DefaultEcs/blob/566186706360454e483137b9aaea3a7682da533b/source/DefaultEcs/Entity.cs#L29
Why do we need WorldId here?
In all of ECS around here (including unity's) that field is unnecessary, due to how entities are stored in worlds

**Comment by Doraku** [comment]
1. short or ushort actually won't make any difference here, as we check for equality here
https://github.com/Doraku/DefaultEcs/blob/566186706360454e483137b9aaea3a7682da533b/source/DefaultEcs/Technical/EntityInfo.cs#L15
Even if it wraps around we are only interested in whether the entity we have stored is the same  as the one known by the world, we don't care about the sign.
At first an Entity was only 2 ints: EntityId and WorldId. When I added the Version I didn't want to change the size of the Entity so I just split the WorldId in two short since hopefully 65535 versions would be enough to not loop around, and you wouldn't have more than 32767 concurrent instances of World at the same time.

2. Which brings me to what is WorldId anyway? As its name implies it is the id, actually the index, of its parent World so it knows where to go to set/get/... component data. The data is stored in a static double array: TComponent[WorldId][EntityId]. The static is need so I can remove all casting with the usage of generic and be eligible for inlining. It is on the Entity just so you can do any operation without the need to keep the World instance.
```
// In Unity
entityMananger.SetComponent(entity, data);

// In DefaultEcs
entity.Set(data);
```
I made this choice because I think it is easier to use that way, even if you lose some space because of it.

While I have not yet created documentation about it because I am still not sure if this feature will stay this way, I added a [`World.GetComponent<T>`](https://github.com/Doraku/DefaultEcs/blob/master/documentation/api/DefaultEcs-World-GetComponents-T-().md) method to get a quick access on component data without the need for the entity to use the WorldId indirection (only for `Get`):
```
Components<T> components = world.GetComponents<T>();

...

ref T component = ref components[entity];
```
Check [this sample](https://github.com/Doraku/DefaultEcs/blob/master/source/Sample/DefaultBoids/System/BoidsSystem.cs#L23) for a "real" usage if you want to squeeze even more performance (up to +30% for some benchmark)

**Comment by RomanZhu** [comment]
I see, thanks for explanation
