### ISSUE TITLE
Serializing with managed resources

### ISSUE THREAD

**Issue by Dancpaz** [Doraku/DefaultEcs#93]
I am trying to convert my project to DefaultECS.  I have been very impressed by what I have seen so far, but I have hit a bit of a wall.

I am trying to create a component with a Texture2D property, and I created an AResourceManager as in the example; however, I am now unable to serialize my world because of a StackOverflowException.  Texture2D contains types with cyclic references.

Ideally, I would tell the system how to handle this with an implementation of something like:
```
interface IResourceConverter<TEntity, TStorage>
{
    TEntity GetEntityValue(TStorage storageValue);
    TStorage GetStorageValue(TEntity entityValue);
}
```

This is what I did in my hand-rolled system before trying to adopt DefaultECS, and I know other systems have something similar.  I briefly toyed with EntityFramework, and I was able to create a converter there which could load Textures.

How do I serialize components with properties like this?  I hope I don't have to set them all to null before serializing and/or maintain a second property for the resource name.

**Comment by Doraku** [comment]
> I hope I don't have to set them all to null before serializing and/or maintain a second property for the resource name.

Sadly this is the current state :/ #32 has been sitting there for a while with no attention from me. Ideally I wanted to pass a list of types to the serializer constructor which would be ignored when serializing components but I like your converter, it would be a good way to sanitize what is serialized.
No promise but since I am working in the serialization zone for a feature I need for my game (some kind of entity factory) I will try to give a proper look on this issue too.

You could create your own `ISerializer` implementation too but... yeah... I am sorry ^^"

**Comment by Dancpaz** [comment]
That's OK.  That and one other perceived issue convinced me to write my own again.

That said, you _did_ inspire me to steal and expand on your syntax!  So thanks for that.  I love the idea of using nice, declarative, fluent queries instead of events or normal method calls.  That's really what attracted me to DefaultECS.

It can't match your performance, but it doesn't need to yet.

**Comment by Doraku** [comment]
Would you mind sharing what is your perceived issue? I am always on the look out for ways to improve or nice features to add, although it might take times to eventually get there (who doesn't hope to do everything they set for even if they don't have the time resource haha).

**Comment by Dancpaz** [comment]
The other may have another way of doing it, which is why I said perceived.
I would like to reference other entities without setting up a formal
relationship between them.  I tried storing the Entity struct, but this was
broken after deserializing.

**Comment by Doraku** [comment]
So I added a `Predicate<Type>` parameter to both serializers constructor so you can filter in or out which component types get actually serialized (hum typing that I should probably add the same logic to what get deserialized too >_>).
As for the conversion problem, this is what I came up with:
```csharp
public interface IMarshaller
{
    IMarshaller Marshal<TIn, TOut>(Func<TIn, TOut> converter);
    IMarshaller Unmarshal<TIn, TOut>(Func<TIn, TOut> converter);
}

public BinarySerializer(Action<IMarshaller> marshalling)

//usage
new BinarySerializer(m => m
    .Marshal<Texture2D, Texture2D>(t => default), // will cleanup Texture2D to null in what is serialized
    .Marshal<Resource, string>(r => r.Name), // Resource will be replaced by a string when serialized, definitely use a more specific type than string in a real case
    .Unmarshal<string, Resource>(s => new Resource(s))); // string will be transformed as a Resource when deserialized
```
It still needs some work but that's the gist of it.



> I would like to reference other entities without setting up a formal relationship between them. I tried storing the Entity struct, but this was broken after deserializing.

Yeah directly serializing an Entity would not work, it is just a pair of index which would not make sense in a new program instance. That's why the `ISerializer` is here with explicit `Entity` and `World` serialization/deserialization. One way you could do it is by using an Id component and use a `EntityMap<Id>` so your system can find which `Entity` it actually reference.
```csharp
public struct EntityRef
{
    public readonly Guid Id;
    ...
}

Entity parent;
Entity child;

Guid id = Guid.New();
parent.Set(id);
child.Set(new EntityRef(id));

...

EntityMap<Guid> map = world.GetEntities.AsMap<Guid>();
child.Set(map[child.Get<EntityRef>().Id]); // on deserialization
```

**Comment by Doraku** [comment]
Well I think I went overboard with this but at least now it's done. You will be able to create `BinarySerializationContext` and `TextSerializationContext` objects to set up your Marshal/Unmarshal convertion. These will be used to convert full component type when serializing worlds or entities or internally inside the type fields. Those object can be reused in multiple serialization/deserialization operations and you can update the conversion between usage.
